"""initial migration

Revision ID: 583835525c6f
Revises: None
Create Date: 2016-11-12 10:38:24.715041

"""

# revision identifiers, used by Alembic.
revision = '583835525c6f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cnt', sa.Integer(), nullable=True),
    sa.Column('intro', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_name', 'group', ['name'], unique=False)
    op.create_table('spider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cnt', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('intro', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spider_name', 'spider', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spider_name', 'spider')
    op.drop_table('spider')
    op.drop_index('ix_group_name', 'group')
    op.drop_table('group')
    ### end Alembic commands ###
